### ISSUE TITLE
在手机上运行为什么hook不了？

### ISSUE THREAD

**Issue by hahaha1230321** [ruoxue/alipay#1]
看日志提示fail
08-15 00:29:02.453 I/Xposed  (  312): Loading modules from /data/app/cn.sanlicun.pay-1/base.apk
08-15 00:29:02.587 I/Xposed  (  312):   Loading class cn.sanlicun.pay.PluginMain
08-15 00:29:02.593 E/Xposed  (  312):     Failed to load class cn.sanlicun.pay.PluginMain
08-15 00:29:02.593 E/Xposed  (  312): java.lang.ClassNotFoundException: Didn't find class "cn.sanlicun.pay.PluginMain" on path: DexPathList[[zip file "/data/app/cn.sanlicun.pay-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
08-15 00:29:02.593 E/Xposed  (  312):

**Comment by ruoxue** [comment]
项目转移[alipayqq ](https://github.com/ruoxue/Alipayqq)
